### ISSUE TITLE
Revert support to multiple module systems

### ISSUE THREAD

**Issue by vdyalex** [ShogunPanda/http-errors-enhanced#1]
Dear @ShogunPanda,

On version `1.x`, the [support to CommonJS was dropped](https://github.com/ShogunPanda/http-errors-enhanced/commit/189d8f3e5efafc62b7361eea7a3d3e64a56aca43) but without apparent reported issues while it was stable on version `0.x`.

It is not clear the motivation, as it's open-source and used by some organizations. I would kindly ask for the reasons why it has been dropped and offer my spare hours to contribute to the solution of eventual problems.

**Comment by ShogunPanda** [comment]
Hello!

Not sure what happened in the changelog, but the change is actually listed here: https://github.com/ShogunPanda/http-errors-enhanced/releases/tag/v1.0.0-beta.0

Anyway, I chose to drop support for CJS as I believe the future of Node is ESM and I'm trying to help to migrate the community towards it. So I dropped support for ESM in all my public packages.

As this is was a breaking change, I included in a semver-major release.
Thanks!

**Comment by Zach-Jaensch** [comment]
I would have loved to support you, instead your documentation about "just turn on this experimental flag" turn us, as well as many others, away. I understand your opinion of ESM being the future, but between now and then, I imagine there will be a package that is heavily inspired by http-errors-enhanced that solves the issue of usability in the short term and still enables the progress towards a different standard. 

Thank you for the time you took creating this package, I am saddened I am not afforded the opportunity to rearchitect our applications to use it.

**Comment by ShogunPanda** [comment]
I'm sorry, may I ask you which "experimental flag" are you talking about? I just wonder if there is some mistake in the docs.
