### ISSUE TITLE
Could not find typings

### ISSUE THREAD

**Issue by blahbleepew** [ShogunPanda/http-errors-enhanced#2]
I can't seem to find any typings when I try to use this with a typescript project that has "moduleResolution": "nodenext"

`Could not find a declaration file for module 'http-errors-enhanced'.`

**Comment by ShogunPanda** [comment]
This should have been fixed in [v1.0.11](https://github.com/ShogunPanda/http-errors-enhanced/releases/tag/v1.0.11). Could you please double check?

**Comment by blahbleepew** [comment]
very cool, thank you!

**Comment by ShogunPanda** [comment]
Fixed in [v1.0.11](https://github.com/ShogunPanda/http-errors-enhanced/releases/tag/v1.0.11).
